# Generated by Django 4.0.3 on 2022-05-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='okuser',
            options={'ordering': ('id', 'first_name')},
        ),
        migrations.AddField(
            model_name='okuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='okuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
